apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  local:
    serverCertSANs:
    - 127.0.0.1
    - localhost
    - node1
    - 192.168.1.70
    peerCertSANs:
    - 127.0.0.1
    - localhost
    - node1
    - 192.168.1.70
    dataDir: /var/lib/etcd


